[package]
name = "code-executor"
version = "2.0.1"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/akagiyuu/code-executor"
homepage = "https://github.com/akagiyuu/code-executor"
description = """
A library designed for the backend of competitive programming platforms
"""

[dependencies]
libseccomp = "0.4.0"
nix = { version = "0.30.0", features = ["fs", "process", "resource", "signal"] }
quickcheck_macros = "1.0.0"
state-shift = "2.1.1"
thiserror = "2.0.9"

[dev-dependencies]
rstest = "0.25.0"
