on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  test:
    name: Run test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: stable

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            toolchain: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          components: llvm-tools-preview

      - name: Init rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo nextest
        uses: taiki-e/install-action@nextest

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openjdk-8-jdk build-essential python3 python-is-python3 libseccomp-dev libgbm-dev libxkbcommon-x11-0 pkg-config rustc

      - name: Run test
        run: |
          cargo nextest run --target ${{ matrix.target }}
